### ISSUE TITLE
`stack_collapse` panic

### ISSUE THREAD

**Issue by Imberflur** [rust-lang/measureme#71]
Not sure if I'm doing something wrong
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"codegen_crate"`,
 right: `"codegen_and_optimize_crate"`', stack_collapse/src/stack_collapse.rs:46:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: stack_collapse::stack_collapse::collapse_stacks
             at stack_collapse/src/stack_collapse.rs:46
   8: stack_collapse::main
             at stack_collapse/src/main.rs:34
   9: std::rt::lang_start::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  10: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  12: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  13: std::rt::lang_start
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by wesleywiser** [comment]
I suspect you're probably running into https://github.com/rust-lang/rust/pull/65137 so if you update your compiler to a more recent nightly, it will likely work.

**Comment by Imberflur** [comment]
That was it, thanks for the help!
